# Generated by Django 4.0.6 on 2022-07-06 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='日時'),
            preserve_default=False,
        ),
    ]
